apiVersion: v1
kind: Service
metadata:
  name: invpy-service
  namespace: invpy
spec:
  selector:
    app: invpy
  ports:
    - name: invpy-port
      protocol: TCP
      port: 3000
      targetPort: 8000
