# Generated by Django 4.1.7 on 2023-03-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_item_created_at_item_updated_at_make_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Time'),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Time'),
        ),
        migrations.AlterField(
            model_name='make',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Time'),
        ),
        migrations.AlterField(
            model_name='make',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Time'),
        ),
        migrations.AlterField(
            model_name='model',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Time'),
        ),
        migrations.AlterField(
            model_name='model',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Time'),
        ),
        migrations.AlterField(
            model_name='part',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Time'),
        ),
        migrations.AlterField(
            model_name='part',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Time'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Time'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Time'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Time'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Time'),
        ),
    ]
