# Generated by Django 4.1.7 on 2023-04-01 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_item_created_at_alter_item_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='task',
        ),
    ]
