# Generated by Django 4.1.7 on 2023-04-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_project_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='cpu',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='disk0',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='disk1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='disk2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='disk3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='mem',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='desc',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='make',
            name='desc',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='model',
            name='desc',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='part',
            name='desc',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='task',
            name='desc',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
