# Generated by Django 4.1.7 on 2023-04-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_status_item_cpu_item_disk0_item_disk1_item_disk2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
