# Generated by Django 4.1.7 on 2023-04-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_status_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='spec',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
