# Generated by Django 4.1.7 on 2023-06-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_item_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='disk4',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
